---
title: "geo_analysis"
author: "whzemuch"
date: "January 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r library and import data}
library(GEOquery)
library(limma) 



gse <- getGEO("GSE781",GSEMatrix=FALSE, destdir = "./data.", getGPL = F)

gset <-  getGEO("GSE32575", destdir = "./data/", getGPL = F)



structure(gse)

```
```{r}
## get ExpressionSet and group information
exprSet <- exprs(gset[[1]])

pdata <- pData(gset[[1]])
group_list=c(rep('before',18),rep('after',18))

group_list=factor(group_list)
group_list <- relevel(group_list, ref="before")


boxplot(exprSet,outline=FALSE, notch=T,col=group_list, las=2)


exprSet=normalizeBetweenArrays(exprSet)
boxplot(exprSet,outline=FALSE, notch=T,col=group_list, las=2)




```

```{r data transformation using log2}
exprSet = as.data.frame(exprSet)[,-seq(1,12)]

## from GEO2R
ex <- exprSet
qx <- as.numeric(quantile(ex, c(0., 0.25, 0.5, 0.75, 0.99, 1.0), na.rm=T))
LogC <- (qx[5] > 100) ||
  (qx[6]-qx[1] > 50 && qx[2] > 0) ||
  (qx[2] > 0 && qx[2] < 1 && qx[4] > 1 && qx[4] < 2)

if(LogC) {
    ex[which(ex <= 0)] <- NaN
    exprSet <- log2(ex)
    print("log2 tranform finished")
} else {
    print ("log2 transfromation not needed")
}

```
```{r}
"illuminaHumanv2.db"

安装R包并加载

# if(length(getOption("BioC_mirror"))==0) options(BioC_mirror="https://mirrors.ustc.edu.cn/bioc/")
if(!require("illuminaHumanv2.db")) BiocManager::install("illuminaHumanv2.db",update = F,ask = F)
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("illuminaHumanv2.db", version = "3.8")

## structure(gset) > annotaion:GPL6102, accoriding to platformMap made by Guozi, we need illuinaHumanv2.db package.

library(illuminaHumanv2.db, character.only = TRUE)

platformDB <- "illuminaHumanv2.db"

probeset <-  rownames(exprSet)
SYMBOL <- annotate::lookUp(probeset, platformDB, "SYMBOL")

symbol <- as.vector(unlist(SYMBOL))
probe2symbol <- data.frame(probeset, symbol, stringsAsFactors = F)


```

